# Generated by Django 5.2.14 on 2026-05-25 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('source_type', models.CharField(choices=[('sap_fuel_procurement', 'SAP fuel and procurement'), ('utility_electricity', 'Utility electricity'), ('corporate_travel', 'Corporate travel')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='ingestion.company')),
            ],
            options={
                'ordering': ['company', 'name'],
                'unique_together': {('company', 'source_type')},
            },
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap_fuel_procurement', 'SAP fuel and procurement'), ('utility_electricity', 'Utility electricity'), ('corporate_travel', 'Corporate travel')], max_length=40)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], max_length=20)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('facility_code', models.CharField(blank=True, max_length=80)),
                ('category', models.CharField(max_length=120)),
                ('subcategory', models.CharField(blank=True, max_length=120)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('unit', models.CharField(max_length=40)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('normalized_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('warning', 'Warning'), ('failed', 'Failed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='valid', max_length=20)),
                ('duplicate_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('approved_by', models.CharField(blank=True, max_length=180)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingestion.company')),
            ],
            options={
                'ordering': ['-batch__created_at', 'raw_record__row_number'],
            },
        ),
        migrations.CreateModel(
            name='AnalystReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=180)),
                ('decision', models.CharField(choices=[('valid', 'Valid'), ('warning', 'Warning'), ('failed', 'Failed'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('normalized_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ingestion.normalizedrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('source_row_hash', models.CharField(db_index=True, max_length=64)),
                ('raw_data', models.JSONField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('warning', 'Warning'), ('failed', 'Failed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='valid', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.company')),
            ],
            options={
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='raw_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_record', to='ingestion.rawrecord'),
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_by', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('warning', 'Warning'), ('failed', 'Failed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='valid', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('warning_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('approved_rows', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_batches', to='ingestion.company')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_batches', to='ingestion.datasource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='rawrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.uploadbatch'),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingestion.uploadbatch'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('actor', models.CharField(blank=True, max_length=180)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.company')),
                ('normalized_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ingestion.normalizedrecord')),
                ('raw_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ingestion.rawrecord')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ingestion.uploadbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error')], max_length=20)),
                ('message', models.TextField()),
                ('field', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('normalized_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_issues', to='ingestion.normalizedrecord')),
            ],
            options={
                'ordering': ['normalized_record_id', '-severity', 'rule_code'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='rawrecord',
            unique_together={('batch', 'row_number')},
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['company', 'status'], name='ingestion_n_company_c5eef8_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['company', 'scope'], name='ingestion_n_company_8ae271_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['company', 'source_type'], name='ingestion_n_company_01ec03_idx'),
        ),
    ]
